language: php

php:
  - 5.5.9
  - 7.0
  - 7.1
  - 7.2
  - hhvm

env:
  global:
    - DRIVER_VERSION="stable"
    - ADAPTER_VERSION="^1.0.0"
    - WITH_ODM=1

services:
  - mongodb

matrix:
  fast_finish: true
  include:
    # test lowest version
    - php: 5.5.9
      env: COMPOSER_FLAGS="--prefer-lowest"

    # test the latest stable 2.8 release (php 5.3)
    - php: 5.5.9
      env: SYMFONY_VERSION=^2.8

    # test the latest stable 3.x release (php 5.5)
    - php: 5.5.9
      env: SYMFONY_VERSION=^3.0

    # test the latest stable 3.x release (php 7.0)
    - php: 7.0
      env: SYMFONY_VERSION=^3.0

    # test the latest stable 3.x release  (php 7.1)
    - php: 7.1
      env: SYMFONY_VERSION=^3.0

    # test the latest stable 3.x release  (php 7.2)
    - php: 7.2
      env: SYMFONY_VERSION=^3.0

    # test the latest release (including beta releases)
    - php: 7.1
      env: DEPENDENCIES=beta
  allow_failures:
    - php: hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if [ "$DEPENDENCIES" = "beta" ]; then composer config minimum-stability beta; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;
  # MongoDB
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "5." ]]; then yes '' | pecl -q install -f mongo-${DRIVER_VERSION}; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then pecl install -f mongodb-${DRIVER_VERSION}; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then composer config "platform.ext-mongo" "1.6.16" && composer require "alcaeus/mongo-php-adapter=${ADAPTER_VERSION}" --no-update; fi
  - if [[ "$WITH_ODM" = 1 ]]; then composer require doctrine/mongodb-odm-bundle --no-update; fi;

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
 - ./vendor/bin/phpunit
